/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import java.io.InputStreamReader;

import org.json.JSONObject;
import org.junit.Test;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

public class AllTest {
	@Test 
	public void testApacheJson() throws Exception {
		String jsonText = apache.Main.jsonTextFromUrl(requetes.Main.GIT);

		JSONObject json = new JSONObject(jsonText);

		int totalCount = (int) json.get("total_count");

		assertEquals("apche+json", 5,totalCount);
	}

	@Test
	public void testGson() throws Exception {
		InputStreamReader jsonReader = standard.Main.jsonStreamFromUrl(requetes.Main.GIT);

		// Convert to a JSON object to print data
		JsonParser jp = new JsonParser(); //from gson


		JsonElement root = jp.parse(jsonReader); //Convert the input stream to a json element
		JsonObject rootobj = root.getAsJsonObject(); //May be an array, may be an object. 
		int totalCount = rootobj.get("total_count").getAsInt(); //just grab the total_count

		assertEquals("gson", 5,totalCount);
	}
	
	@Test
	public void testJson() throws Exception {
		String jsonText = standard.Main.jsonTextFromUrl(requetes.Main.GIT);

		JSONObject json = new JSONObject(jsonText);

		int totalCount = (int) json.get("total_count");

		assertEquals("json", 5,totalCount);
	}
}
