/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import static org.junit.Assert.assertEquals;

import java.io.IOException;
import java.net.MalformedURLException;

import org.json.JSONException;
import org.json.JSONObject;
import org.junit.Test;

public class AllTest {
	@Test 
	public void testApacheJson() 
			throws MalformedURLException, IOException, JSONException {
		
		assertEquals("apche+json", "4",apache.Main.getField(requetes.Main.GIT, "total_count"));
	}
	
	@Test
	public void testGson() throws IOException {
	
		assertEquals("gson", "4",gson.Main.getField(requetes.Main.GIT, "total_count"));
	}
	
	@Test
	public void testJackson() throws IOException {
		
		assertEquals("jackson", "4",jackson.Main.getField(requetes.Main.GIT, "total_count"));
	}
	
	
	@Test
	public void testJson() throws Exception {
		String jsonText = standard.Main.jsonTextFromUrl(requetes.Main.GIT);

		JSONObject json = new JSONObject(jsonText);

		int totalCount = (int) json.get("total_count");

		assertEquals("json", 4,totalCount);
	}
}
